version: '3.3'
services:

  postgres:
    image: postgres
    restart: always
    container_name: usermsdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test


