server:
  port: 8083
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USER:test}
    password: ${DATABASE_SEC:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create

client:
  ms-user:
   auth:
    url: "http://localhost:8081/auth/user-details"